-- 무기 고정 개조 부품 + 무기 개조 부품 보강 (Raigulus Build Maker와 항목 맞춤).
-- 확인일: 2026-09-26
--
-- [weapon_fixed_mods] 특급 무기(44정)가 가진 고정 부품과 일부 일반/네임드 무기의 고정 부품.
--   출처: 부품 이름·효과는 나무위키 "톰 클랜시의 디비전 2/특급 장비" 각 무기 "부착물" 항목(한국어 원문 그대로).
--         어느 슬롯에 들어가는지는 Raigulus(div2hub/game-data, Y8S3)의 슬롯 정보와 나무위키의
--         [광학 레일]/[탄창 슬롯] 등 태그로 맞췄다. 나무위키와 Raigulus의 효과 수치가 다른 부품
--         (패치 차이)은 나무위키 수치를 썼다.
--   나무위키에 효과 수치가 없는 부품(탄환 제왕 "저장의 탄창")은 effect_ko를 빈 문자열로 둔다.
--   일반/네임드 고정 부품 중 "QDC 소음기"(Stoner LAMG, 소리 없는 아우성)와 "내장 조준경(8x)"(GR9, 담력, 크리켓)의
--   한국어 이름은 나무위키에 부품 이름이 없어("신속 탈착 결합부", "8배율 내장 조준경" 서술만 있음) 붙인 이름이고,
--   효과 수치는 Raigulus 값이다. 게임 화면과 다르면 name_ko만 고치면 된다.
--   특급 무기 중 "버티고(Vertigo)"는 나무위키에는 있으나 weapon_exotic에 없어 빠져 있다.

create table weapon_fixed_mods (
  id bigint generated always as identity primary key,
  weapon_name_ko text not null,   -- weapon_models / weapon_named / weapon_exotic의 name_ko
  weapon_name_en text not null,
  slot text not null,             -- optic | magazine | underbarrel | muzzle
  name_ko text not null,
  effect_ko text not null default ''
);
alter table weapon_fixed_mods enable row level security;
create policy "public read" on weapon_fixed_mods for select using (true);

insert into weapon_fixed_mods (weapon_name_ko, weapon_name_en, slot, name_ko, effect_ko) values
('독수리를 거느린 자', 'Eagle Bearer', 'optic', '독수리의 눈 조준기', '+15% 치명타 확률'),
('독수리를 거느린 자', 'Eagle Bearer', 'magazine', '탄환의 둥지', '+30 탄약'),
('독수리를 거느린 자', 'Eagle Bearer', 'underbarrel', '갈퀴 손잡이', '+10% 무기 조작력'),
('독수리를 거느린 자', 'Eagle Bearer', 'muzzle', '뾰족한 부리', '+20% 치명타 대미지'),
('카멜레온', 'Chameleon', 'optic', '카멜레온 광학 조준기', '+15% 치명타 확률'),
('카멜레온', 'Chameleon', 'magazine', '카멜레온 능동 위장 프로세서', '+20 탄약'),
('카멜레온', 'Chameleon', 'underbarrel', '카멜레온 손잡이', '+10% 안정성'),
('카멜레온', 'Chameleon', 'muzzle', '카멜레온 중화 장치', '+20% 명중률'),
('빅혼', 'The Bighorn', 'optic', '사격 지정 조준경', '+30% 헤드샷 대미지'),
('빅혼', 'The Bighorn', 'magazine', '인장 스프링 탄창', '+10% 재장전 속도'),
('빅혼', 'The Bighorn', 'underbarrel', '빅혼 뿔 손잡이', '+20% 안정성'),
('빅혼', 'The Bighorn', 'muzzle', '탄소강 총구', '+10% 명중률'),
('축전기', 'Capacitor', 'optic', '전도성 초점', '+10% 치명타 확률'),
('축전기', 'Capacitor', 'magazine', '전압원', '+11 탄약'),
('축전기', 'Capacitor', 'underbarrel', '절연성 안전 손잡이', '+10% 무기 조작력'),
('축전기', 'Capacitor', 'muzzle', '방전극', '+30% 치명타 대미지'),
('성 엘모의 엔진', 'St. Elmo''s Engine', 'optic', '전도체 레일', '+15% 치명타 대미지'),
('성 엘모의 엔진', 'St. Elmo''s Engine', 'magazine', '단열 탄창', '+30 탄약'),
('성 엘모의 엔진', 'St. Elmo''s Engine', 'underbarrel', '단열 손잡이', '+10% 무기 조작력'),
('성 엘모의 엔진', 'St. Elmo''s Engine', 'muzzle', '과충전 총구', '+15% 치명타 확률'),
('스트레가', 'Strega', 'optic', '스트레가 광학 장비', '+5% 치명타 대미지'),
('스트레가', 'Strega', 'magazine', '스트레가 탄창', '+20 탄약'),
('스트레가', 'Strega', 'underbarrel', '상원 손잡이', '+10% 무기 조작력'),
('스트레가', 'Strega', 'muzzle', '스트레가 총구', '+5% 치명타 확률'),
('선동가', 'Agitator', 'optic', '선동가 조준경', '+10% 치명타 확률'),
('선동가', 'Agitator', 'magazine', '선동가 탄창', '+20 탄약'),
('선동가', 'Agitator', 'muzzle', '선동가 총구', '+50% 교체 속도'),
('카두세우스', 'Caduceus', 'optic', '카두세우스 광학 조준기', '+10% 치명타 확률'),
('카두세우스', 'Caduceus', 'magazine', '카두세우스 탄창', '+40 탄약'),
('카두세우스', 'Caduceus', 'underbarrel', '카두세우스 총열 하단부', '+5% 치명타 대미지'),
('카두세우스', 'Caduceus', 'muzzle', '카두세우스 총구', '+5% 치명타 확률'),
('촉새', 'The Chatterbox', 'optic', '개조된 광학 조준기', '+15% 치명타 확률'),
('촉새', 'The Chatterbox', 'magazine', '촉새 탄창', '+10 탄약'),
('촉새', 'The Chatterbox', 'underbarrel', '촉새 용기', '+10% 무기 조작력'),
('촉새', 'The Chatterbox', 'muzzle', '촉새 총구', '+15% 치명타 대미지'),
('죽음의 귀부인', 'Lady Death', 'optic', '죽음의 시선', '+15% 치명타 확률'),
('죽음의 귀부인', 'Lady Death', 'magazine', '죽음의 머리', '+10% 재장전 속도'),
('죽음의 귀부인', 'Lady Death', 'underbarrel', '죽음의 입맞춤', '+500% 근접 대미지'),
('죽음의 귀부인', 'Lady Death', 'muzzle', '죽음의 턱', '+10% 치명타 대미지'),
('역화', 'Backfire', 'optic', '쾌속 조준기', '+15% 치명타 확률'),
('역화', 'Backfire', 'magazine', '가시 손잡이 탄창', '+20 탄약'),
('역화', 'Backfire', 'underbarrel', '가시 프레임', '+10% 안정성'),
('역화', 'Backfire', 'muzzle', '톱니 총구', '+15% 치명타 대미지'),
('우로보로스', 'Ouroboros', 'optic', '우로보로스 조준기', '+10% 치명타 대미지'),
('우로보로스', 'Ouroboros', 'magazine', '우로보로스 탄창', '+25% 재장전 속도'),
('우로보로스', 'Ouroboros', 'underbarrel', '우로보로스 총열 하단부', '+10% 치명타 확률'),
('우로보로스', 'Ouroboros', 'muzzle', '우로보로스 총구', '+10% 발사 속도'),
('옥스페커', 'Oxpecker', 'optic', '옥스페커 광학 조준기', '+50% 적정 사거리'),
('옥스페커', 'Oxpecker', 'underbarrel', '옥스페커 총열 하단부', '+15% 치명타 확률'),
('옥스페커', 'Oxpecker', 'muzzle', '옥스페커 총구', '+10 탄약'),
('부두목', 'Underboss', 'optic', '조준경', '+20% 치명타 확률'),
('역병', 'Pestilence', 'magazine', '역병에 오염된 탄창', '+10% 발사 속도'),
('역병', 'Pestilence', 'underbarrel', '역병에 오염된 덕트 테이프', '+10% 안정성'),
('역병', 'Pestilence', 'muzzle', '역병에 오염된 총구', '+10% 명중률'),
('탄환 제왕', 'Bullet King', 'magazine', '저장의 탄창', ''),
('탄환 제왕', 'Bullet King', 'underbarrel', '순금 양각대', '+20% 안정성'),
('탄환 제왕', 'Bullet King', 'muzzle', '금도금 총구', '+15% 치명타 확률'),
('블루스크린', 'Bluescreen', 'optic', '라이트닝 조준기', '+20% 재장전 속도'),
('블루스크린', 'Bluescreen', 'magazine', '인증 철회 프레임', '+15% 무기 조작력'),
('블루스크린', 'Bluescreen', 'underbarrel', '오버클럭 총구', '+20% 발사 속도'),
('블루스크린', 'Bluescreen', 'muzzle', '드롭킥 손잡이', '+10% 안정성'),
('강철의 허파', 'Iron Lung', 'magazine', '풀무', '+35 탄약'),
('강철의 허파', 'Iron Lung', 'underbarrel', '비늘', '+20% 치명타 대미지'),
('강철의 허파', 'Iron Lung', 'muzzle', '용의 뿔', '+10% 치명타 확률'),
('파칸', 'Pakhan', 'optic', '파칸 조준기', '+15% 무기 대미지'),
('파칸', 'Pakhan', 'magazine', '파칸 탄창', '+20 탄약'),
('파칸', 'Pakhan', 'underbarrel', '파칸 총열 하단부', '+10% 재장전 속도'),
('파칸', 'Pakhan', 'muzzle', '파칸 총구', '+15% 치명타 확률'),
('달콤한 꿈', 'Sweet Dreams', 'optic', '아웃캐스트 광학 조준기', '+15% 명중률'),
('달콤한 꿈', 'Sweet Dreams', 'magazine', '개조 급탄 시스템', '+15% 재장전 속도'),
('달콤한 꿈', 'Sweet Dreams', 'underbarrel', '스터너', '+25% 적정 사거리'),
('스콜피오', 'Scorpio', 'optic', '별빛 수용기', '+10% 치명타 확률'),
('스콜피오', 'Scorpio', 'magazine', '맹독샘', '+10% 재장전 속도'),
('스콜피오', 'Scorpio', 'underbarrel', '킬레 손잡이', '+10% 무기 조작력'),
('스콜피오', 'Scorpio', 'muzzle', '독침', '+10% 안정성'),
('오버로드', 'Overlord', 'optic', '오버로드 광학 조준기', '+15% 치명타 대미지'),
('오버로드', 'Overlord', 'magazine', '오버로드 탄창', '+15% 재장전 속도'),
('오버로드', 'Overlord', 'underbarrel', '오버로드 총열 하단부 손잡이', '+20% 안정성'),
('파프니르', 'Fafnir', 'optic', '파프니르 광학 조준기', '+15% 치명타 확률'),
('파프니르', 'Fafnir', 'magazine', '파프니르 탄창', '+5 탄약'),
('파프니르', 'Fafnir', 'underbarrel', '파프니르 총열 하단부', '+10% 무기 조작력'),
('네메시스', 'Nemesis', 'optic', '네메시스 디지털 조준경', '+45% 헤드샷 대미지'),
('네메시스', 'Nemesis', 'magazine', '네메시스 볼트', '+10% 재장전 속도'),
('네메시스', 'Nemesis', 'underbarrel', '네메시스 양각대', '+5% 무기 조작력'),
('네메시스', 'Nemesis', 'muzzle', '네메시스 총열', '+5% 치명타 대미지'),
('사마귀', 'Mantis', 'optic', '눈부심 방지 코팅 조준기', '+40% 헤드샷 대미지'),
('사마귀', 'Mantis', 'magazine', '기름칠한 스프링', '+10% 재장전 속도'),
('사마귀', 'Mantis', 'underbarrel', '길리 프레임', '+10% 안정성'),
('사마귀', 'Mantis', 'muzzle', '소염기', '+5% 치명타 확률'),
('공포의 칙령', 'Dread Edict', 'optic', '심판의 시선', '+40% 헤드샷 대미지'),
('공포의 칙령', 'Dread Edict', 'magazine', '장력 조율 스프링', '+15% 무기 조작력'),
('공포의 칙령', 'Dread Edict', 'underbarrel', '무쌍 프레임', '+10% 안정성'),
('공포의 칙령', 'Dread Edict', 'muzzle', '마침표 총열', '+10% 치명타 확률'),
('신성 제국', 'Sacrum Imperium', 'optic', '신성 광학 조준기', '+20% 헤드샷 대미지'),
('신성 제국', 'Sacrum Imperium', 'magazine', '신성 탄창', '+10% 헤드샷 대미지'),
('신성 제국', 'Sacrum Imperium', 'underbarrel', '신성 총열 하단부', '+20% 안정성'),
('신성 제국', 'Sacrum Imperium', 'muzzle', '신성 총구', '+20% 적정 사거리'),
('슈라우드', 'Shroud', 'optic', '슈라우드 조준경', '+25% 헤드샷 대미지'),
('슈라우드', 'Shroud', 'magazine', '슈라우드 탄창', '+20% 재장전 속도'),
('슈라우드', 'Shroud', 'underbarrel', '슈라우드 총열 하단부', '+5% 치명타 대미지'),
('슈라우드', 'Shroud', 'muzzle', '슈라우드 총구', '+20% 헤드샷 대미지'),
('프리마돈나', 'Prima Donna', 'optic', '프리마돈나 조준경', '+25% 헤드샷 대미지'),
('프리마돈나', 'Prima Donna', 'magazine', '프리마돈나 탄창', '+7.5% 무기 조작력'),
('프리마돈나', 'Prima Donna', 'underbarrel', '프리마돈나 총열 하단부', '+7.5% 무기 조작력'),
('프리마돈나', 'Prima Donna', 'muzzle', '프리마돈나 총구', '+20% 헤드샷 대미지'),
('무자비', 'Merciless', 'optic', '무자비 광학 조준기', '+10% 명중률'),
('무자비', 'Merciless', 'magazine', '무자비 탄창', '+10% 재장전 속도'),
('무자비', 'Merciless', 'underbarrel', '무자비 손잡이', '+10% 무기 조작력'),
('무자비', 'Merciless', 'muzzle', '무자비 총구', '+10% 안정성'),
('다이아몬드백', 'Diamondback', 'optic', '다이아몬드백 도트사이트', '+10% 명중률'),
('다이아몬드백', 'Diamondback', 'magazine', '다이아몬드백 레버', '+10% 재장전 속도'),
('다이아몬드백', 'Diamondback', 'underbarrel', '다이아몬드백 손잡이', '+10% 안정성'),
('다이아몬드백', 'Diamondback', 'muzzle', '방울뱀 장식', '+15% 치명타 대미지'),
('탐식자', 'The Ravenous', 'optic', '포식자 광학 조준기', '+5% 치명타 확률'),
('탐식자', 'The Ravenous', 'magazine', '게걸스러운 탄창', '+10% 재장전 속도'),
('탐식자', 'The Ravenous', 'underbarrel', '늑대의 발톱', '+10% 안정성'),
('탐식자', 'The Ravenous', 'muzzle', '삼키는 위', '+5% 치명타 대미지'),
('주치의', 'Doctor Home', 'optic', '의사의 혜안', '+10% 명중률'),
('주치의', 'Doctor Home', 'magazine', '가정의 탄창', '+10% 재장전 속도'),
('주치의', 'Doctor Home', 'underbarrel', '의사의 손잡이', '+10% 치명타 확률'),
('주치의', 'Doctor Home', 'muzzle', '의사의 끈기', '+10% 무기 조작력'),
('빈디케이터', 'Vindicator', 'optic', '빈디케이터 조준경', '+15% 명중률'),
('빈디케이터', 'Vindicator', 'magazine', '빈디케이터 탄창', '+5 탄약'),
('빈디케이터', 'Vindicator', 'underbarrel', '빈디케이터 손잡이', '+15% 안정성'),
('빈디케이터', 'Vindicator', 'muzzle', '빈디케이터 총구', '+10% 적정 사거리'),
('달콤 쌉싸름', 'Bittersweet', 'optic', '달콤 쌉싸름 조준경', '+5% 헤드샷 대미지'),
('달콤 쌉싸름', 'Bittersweet', 'magazine', '달콤 쌉싸름 탄창', '+10 탄약'),
('달콤 쌉싸름', 'Bittersweet', 'underbarrel', '달콤 쌉싸름 총열 하단부', '+5% 헤드샷 대미지'),
('스틸 앤 선즈 ACR', 'Steel & Sons ACR', 'optic', '클린 컷 광학 조준기', '+15% 치명타 확률'),
('스틸 앤 선즈 ACR', 'Steel & Sons ACR', 'magazine', '하네스 버클 탄창', '+10 탄약'),
('스틸 앤 선즈 ACR', 'Steel & Sons ACR', 'underbarrel', '헬브 총열 하단부', '+10% 무기 조작력'),
('스틸 앤 선즈 ACR', 'Steel & Sons ACR', 'muzzle', '톱니 총구', '+10% 재장전 속도'),
('자유', 'Liberty', 'optic', '자유 조준기', '+5% 헤드샷 대미지'),
('자유', 'Liberty', 'magazine', '자유 손잡이', '+15% 무기 조작력'),
('자유', 'Liberty', 'underbarrel', '방아쇠 장치', '+15% 발사 속도'),
('자유', 'Liberty', 'muzzle', '자유 맞춤 부품', '+5% 치명타 확률'),
('레굴루스', 'Regulus', 'magazine', '각인 드럼', '+10% 재장전 속도'),
('레굴루스', 'Regulus', 'muzzle', '각인 총구', '+5% 치명타 대미지'),
('바쁜 꼬마 벌', 'Busy Little Bee', 'optic', '벌의 집중', '+25% 적정 사거리'),
('바쁜 꼬마 벌', 'Busy Little Bee', 'magazine', '벌의 속도', '+10% 재장전 속도'),
('바쁜 꼬마 벌', 'Busy Little Bee', 'underbarrel', '벌의 힘', '+5% 치명타 확률'),
('바쁜 꼬마 벌', 'Busy Little Bee', 'muzzle', '벌의 목적의식', '+10% 안정성'),
('모스키토', 'Mosquito', 'magazine', '모스키토 탄창', '+15% 재장전 속도'),
('모스키토', 'Mosquito', 'muzzle', '모스키토 총구', '+15% 명중률'),
('템페스트', 'Tempest', 'magazine', '템페스트 탄창', '+50% 안정성'),
('템페스트', 'Tempest', 'muzzle', '템페스트 총구', '+15% 치명타 확률'),
('위플래쉬', 'Whiplash', 'optic', '위플래쉬 광학 조준기', '+10% 치명타 대미지'),
('위플래쉬', 'Whiplash', 'magazine', '위플래쉬 탄창', '+10% 치명타 확률'),
('위플래쉬', 'Whiplash', 'underbarrel', '위플래쉬 총열 하단부', '+50% 교체 속도'),
('Stoner LAMG', 'Stoner LAMG', 'muzzle', 'QDC 소음기', '+30% 안정성'),
('소리 없는 아우성', 'Quiet Roar', 'muzzle', 'QDC 소음기', '+30% 안정성'),
('GR9', 'GR9', 'optic', '내장 조준경(8x)', '+5% 치명타 확률'),
('담력', 'Dare', 'optic', '내장 조준경(8x)', '+5% 치명타 확률'),
('크리켓', 'Cricket', 'optic', '내장 조준경(8x)', '+5% 치명타 확률'),
('오, 캐롤', 'Oh Carol', 'optic', 'VX1 조준경(12x)', '+35% 헤드샷 대미지, -10% 재장전 속도');

-- [weapon_mods 보강] Raigulus에는 있고 나무위키 제작 문서 표에는 없던 부품 2개.
--   * 대형 파우치(기관포병 전용 탄띠): "기관포병의 대형 파우치 개조"라는 서술만 나무위키에 있고 수치는 Raigulus(+50 장탄수).
--   * QDC 소음기: Raigulus의 QDC Sound Suppressor(+30% 안정성). 나무위키는 Stoner LAMG 총구 슬롯을 "신속 탈착 결합부(전용)"로만 적는다.
insert into weapon_mods (slot, slot_ko, category_ko, name_ko, effect_ko, penalty_ko) values
('magazine', '탄창', '탄띠(기관포병 전용)', '대형 파우치 (기관포병)', '+50 장탄수', ''),
('muzzle', '총구', 'QDC(전용)', 'QDC 소음기', '+30% 안정성', '');
