-- ===== schema =====

create table weapon_models (
  item_key text primary key,
  name_key text,
  name_ko text not null,
  name_en text not null,
  weapon_group text not null,
  family text,
  rarity_tier text,
  rpm numeric,
  base_mag_size integer,
  base_damage numeric,
  optimal_range numeric
);

alter table weapon_models enable row level security;
create policy "public read" on weapon_models for select using (true);


-- ===== seed: weapon_models =====

insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:acr', 'acr', 'ACR', 'ACR', 'ar', 'ACR', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:acre', 'acre', 'ACR-E', 'ACR-E', 'ar', 'ACR-E', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:akm', 'akm', 'AK-M', 'AK-M', 'ar', 'AK-M', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:auga3cqc', 'auga3cqc', 'AUG A3-CQC', 'AUG A3-CQC', 'ar', 'AUG A3-CQC', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarketakm', 'blackmarketakm', '블랙마켓 AK-M', 'Black Market AK-M', 'ar', 'Black Market AK-M', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarketakmreplica', 'blackmarketakmreplica', '블랙마켓 AK-M 리플리카', 'Black Market AK-M Replica', 'ar', 'Black Market AK-M Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:carbine7', 'carbine7', 'Carbine 7', 'Carbine 7', 'ar', 'Carbine 7', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:ctar21', 'ctar21', 'CTAR-21', 'CTAR-21', 'ar', 'CTAR-21', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:customp416g3', 'customp416g3', '커스텀 P416 G3', 'Custom P416 G3', 'ar', 'Custom P416 G3', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:f2000', 'f2000', 'F2000', 'F2000', 'ar', 'F2000', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:f2000replica', 'f2000replica', 'F2000 리플리카', 'F2000 Replica', 'ar', 'F2000 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:fal', 'fal', 'FAL', 'FAL', 'ar', 'FAL', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:falsa58', 'falsa58', 'FAL SA-58', 'FAL SA-58', 'ar', 'FAL SA-58', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:falsa58para', 'falsa58para', 'FAL SA-58 Para', 'FAL SA-58 Para', 'ar', 'FAL SA-58 Para', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:falsa58parareplica', 'falsa58parareplica', 'FAL SA-58 Para 리플리카', 'FAL SA-58 Para Replica', 'ar', 'FAL SA-58 Para Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:famas2010', 'famas2010', 'FAMAS 2010', 'FAMAS 2010', 'ar', 'FAMAS 2010', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:famas2010replica', 'famas2010replica', 'FAMAS 2010 리플리카', 'FAMAS 2010 Replica', 'ar', 'FAMAS 2010 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:g36c', 'g36c', 'G36 C', 'G36 C', 'ar', 'G36 C', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:g36enhanced', 'g36enhanced', '강화형 G36', 'G36 Enhanced', 'ar', 'G36 Enhanced', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:g36enhancedreplica', 'g36enhancedreplica', '강화형 G36 리플리카', 'G36 Enhanced Replica', 'ar', 'G36 Enhanced Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:honeybadger', 'honeybadger', 'Honey Badger', 'Honey Badger', 'ar', 'Honey Badger', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militaryakm', 'militaryakm', '군용 AK-M', 'Military AK-M', 'ar', 'Military AK-M', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militaryg36', 'militaryg36', '군용 G36', 'Military G36', 'ar', 'Military G36', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militaryp416', 'militaryp416', '군용 P416', 'Military P416', 'ar', 'Military P416', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:mk16', 'mk16', 'Mk16', 'Mk16', 'ar', 'Mk16', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:pdr', 'pdr', 'PDR', 'PDR', 'ar', 'PDR', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:policem4', 'policem4', '경찰용 M4', 'Police M4', 'ar', 'Police M4', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:policem4replica', 'policem4replica', '경찰용 M4 리플리카', 'Police M4 Replica', 'ar', 'Police M4 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:sig556', 'sig556', 'SIG 556', 'SIG 556', 'ar', 'SIG 556', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:socommk16', 'socommk16', 'SOCOM Mk16', 'SOCOM Mk16', 'ar', 'SOCOM Mk16', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalmk16', 'tacticalmk16', '전술용 Mk 16', 'Tactical Mk 16', 'ar', 'Tactical Mk 16', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalmk16replica', 'tacticalmk16replica', '전술용 Mk 16 리플리카', 'Tactical Mk 16 Replica', 'ar', 'Tactical Mk 16 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tkb408', 'tkb408', 'TKB-408', 'TKB-408', 'ar', 'TKB-408', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:1886', '1886', '1886', '1886', 'rifle', '1886', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:acrss', 'acrss', 'ACR SS', 'ACR SS', 'rifle', 'ACR SS', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:classicm1a', 'classicm1a', '클래식 M1A', 'Classic M1A', 'rifle', 'Classic M1A', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:lightweightm4', 'lightweightm4', '경량형 M4', 'Lightweight M4', 'rifle', 'Lightweight M4', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:lvoac', 'lvoac', 'LVOA-C', 'LVOA-C', 'rifle', 'LVOA-C', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:lvoacreplica', 'lvoacreplica', 'LVOA-C 리플리카', 'LVOA-C Replica', 'rifle', 'LVOA-C Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m16a2', 'm16a2', 'M16A2', 'M16A2', 'rifle', 'M16A2', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m16a2replica', 'm16a2replica', 'M16A2 리플리카', 'M16A2 Replica', 'rifle', 'M16A2 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m1acqb', 'm1acqb', 'M1A CQB', 'M1A CQB', 'rifle', 'M1A CQB', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m1acqbreplica', 'm1acqbreplica', 'M1A CQB 리플리카', 'M1A CQB Replica', 'rifle', 'M1A CQB Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militarymk17', 'militarymk17', '군용 Mk17', 'Military Mk17', 'rifle', 'Military Mk17', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:policemk17', 'policemk17', '경찰용 Mk.17', 'Police Mk17', 'rifle', 'Police Mk17', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:policemk17replica', 'policemk17replica', '경찰용 Mk.17 리플리카', 'Police Mk17 Replica', 'rifle', 'Police Mk17 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:resolutemk47', 'resolutemk47', 'Resolute MK47', 'Resolute MK47', 'rifle', 'Resolute MK47', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:sig716', 'sig716', 'SIG 716', 'SIG 716', 'rifle', 'SIG 716', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:sig716cqb', 'sig716cqb', 'SIG 716 CQB', 'SIG 716 CQB', 'rifle', 'SIG 716 CQB', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:sig716replica', 'sig716replica', 'SIG 716 리플리카', 'SIG 716 Replica', 'rifle', 'SIG 716 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:socomm1a', 'socomm1a', 'SOCOM M1A', 'SOCOM M1A', 'rifle', 'SOCOM M1A', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:uic15mod2', 'uic15mod2', 'UIC15 MOD2', 'UIC15 MOD2', 'rifle', 'UIC15 MOD2', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:urbanmdr', 'urbanmdr', '도심 MDR', 'Urban MDR', 'rifle', 'Urban MDR', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:urbanmdrreplica', 'urbanmdrreplica', '도심 MDR 리플리카', 'Urban MDR Replica', 'rifle', 'Urban MDR Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:usc45acp', 'usc45acp', 'USC .45 ACP', 'USC .45 ACP', 'rifle', 'USC .45 ACP', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:usc45acpreplica', 'usc45acpreplica', 'USC .45 ACP 리플리카', 'USC .45 ACP Replica', 'rifle', 'USC .45 ACP Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:classicm44carbine', 'classicm44carbine', '클래식 M44 Carbine', 'Classic M44 Carbine', 'dmr', 'Classic M44 Carbine', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:classicm44carbinereplica', 'classicm44carbinereplica', '클래식 M44 Carbine 리플리카', 'Classic M44 Carbine Replica', 'dmr', 'Classic M44 Carbine Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:covertsrs', 'covertsrs', 'Covert SRS', 'Covert SRS', 'dmr', 'Covert SRS', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:customm44', 'customm44', '커스텀 M44', 'Custom M44', 'dmr', 'Custom M44', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:customm44replica', 'customm44replica', '커스텀 M44 리플리카', 'Custom M44 Replica', 'dmr', 'Custom M44 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:g28', 'g28', 'G28', 'G28', 'dmr', 'G28', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:huntingm44', 'huntingm44', '사냥용 M44', 'Hunting M44', 'dmr', 'Hunting M44', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m700carbon', 'm700carbon', 'M700 Carbon', 'M700 Carbon', 'dmr', 'M700 Carbon', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m700carbonreplica', 'm700carbonreplica', 'M700 Carbon 리플리카', 'M700 Carbon Replica', 'dmr', 'M700 Carbon Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m700tactical', 'm700tactical', 'M700 Tactical', 'M700 Tactical', 'dmr', 'M700 Tactical', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:model700', 'model700', 'Model 700', 'Model 700', 'dmr', 'Model 700', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:model700replica', 'model700replica', 'Model 700 리플리카', 'Model 700 Replica', 'dmr', 'Model 700 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:paratroopersvd', 'paratroopersvd', '공수부대용 SVD', 'Paratrooper SVD', 'dmr', 'Paratrooper SVD', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:socommk20ssr', 'socommk20ssr', 'SOCOM Mk20 SSR', 'SOCOM Mk20 SSR', 'dmr', 'SOCOM Mk20 SSR', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:socommk20ssrreplica', 'socommk20ssrreplica', 'SOCOM Mk20 SSR 리플리카', 'SOCOM Mk20 SSR Replica', 'dmr', 'SOCOM Mk20 SSR Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:sr1', 'sr1', 'SR-1', 'SR-1', 'dmr', 'SR-1', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:sr1replica', 'sr1replica', 'SR-1 리플리카', 'SR-1 Replica', 'dmr', 'SR-1 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:srsa1', 'srsa1', 'SRS A1', 'SRS A1', 'dmr', 'SRS A1', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:srsa1replica', 'srsa1replica', 'SRS A1 리플리카', 'SRS A1 Replica', 'dmr', 'SRS A1 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:surplussvd', 'surplussvd', 'Surplus SVD', 'Surplus SVD', 'dmr', 'Surplus SVD', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tactical308', 'tactical308', '전술용 .308', 'Tactical .308', 'dmr', 'Tactical .308', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:auga3paraxs', 'auga3paraxs', 'AUG A3 Para XS', 'AUG A3 Para XS', 'smg', 'AUG A3 Para XS', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarkett821', 'blackmarkett821', '블랙마켓 T821', 'Black Market T821', 'smg', 'Black Market T821', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarkett821replica', 'blackmarkett821replica', '블랙마켓 T821 리플리카', 'Black Market T821 Replica', 'smg', 'Black Market T821 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:cmmgbanshee', 'cmmgbanshee', 'CMMG Banshee', 'CMMG Banshee', 'smg', 'CMMG Banshee', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:convertedsmg9', 'convertedsmg9', '개조형 SMG-9', 'Converted SMG-9', 'smg', 'Converted SMG-9', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:convertedsmg9a2', 'convertedsmg9a2', '개조형 SMG-9 A2', 'Converted SMG-9 A2', 'smg', 'Converted SMG-9 A2', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:convertedsmg9replica', 'convertedsmg9replica', '개조형 SMG-9 리플리카', 'Converted SMG-9 Replica', 'smg', 'Converted SMG-9 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:enhancedauga3p', 'enhancedauga3p', '강화형 AUG A3P', 'Enhanced AUG A3P', 'smg', 'Enhanced AUG A3P', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:enhancedpp19', 'enhancedpp19', '강화형 PP-19', 'Enhanced PP-19', 'smg', 'Enhanced PP-19', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m1928', 'm1928', 'M1928', 'M1928', 'smg', 'M1928', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:mp5st', 'mp5st', 'MP5 ST', 'MP5 ST', 'smg', 'MP5 ST', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:mp5streplica', 'mp5streplica', 'MP5 ST 리플리카', 'MP5 ST Replica', 'smg', 'MP5 ST Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:mp5n', 'mp5n', 'MP5-N', 'MP5-N', 'smg', 'MP5-N', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:mp5a2', 'mp5a2', 'MP5A2', 'MP5A2', 'smg', 'MP5A2', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:mp7', 'mp7', 'MP7', 'MP7', 'smg', 'MP7', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:p90', 'p90', 'P90', 'P90', 'smg', 'P90', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:p90replica', 'p90replica', 'P90 리플리카', 'P90 Replica', 'smg', 'P90 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:policet821', 'policet821', '경찰용 T821', 'Police T821', 'smg', 'Police T821', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:policeump45', 'policeump45', '경찰용 UMP-45', 'Police UMP-45', 'smg', 'Police UMP-45', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:pp19', 'pp19', 'PP-19', 'PP-19', 'smg', 'PP-19', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:sigmpx', 'sigmpx', 'SIG MPX', 'SIG MPX', 'smg', 'SIG MPX', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalauga3p', 'tacticalauga3p', '전술용 AUG A3P', 'Tactical AUG A3P', 'smg', 'Tactical AUG A3P', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalauga3preplica', 'tacticalauga3preplica', '전술용 AUG A3P 리플리카', 'Tactical AUG A3P Replica', 'smg', 'Tactical AUG A3P Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalump45', 'tacticalump45', '전술용 UMP-45', 'Tactical UMP-45', 'smg', 'Tactical UMP-45', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalump45replica', 'tacticalump45replica', '전술용 UMP-45 리플리카', 'Tactical UMP-45 Replica', 'smg', 'Tactical UMP-45 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalvectorsbr9mm', 'tacticalvectorsbr9mm', '전술용 Vector SBR 9mm', 'Tactical Vector SBR 9mm', 'smg', 'Tactical Vector SBR 9mm', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tommygun', 'tommygun', 'Tommy Gun', 'Tommy Gun', 'smg', 'Tommy Gun', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:vectorsbr45acp', 'vectorsbr45acp', 'Vector SBR .45 ACP', 'Vector SBR .45 ACP', 'smg', 'Vector SBR .45 ACP', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:vectorsbr45acpreplica', 'vectorsbr45acpreplica', 'Vector SBR .45 ACP 리플리카', 'Vector SBR .45 ACP Replica', 'smg', 'Vector SBR .45 ACP Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:vectorsbr9mm', 'vectorsbr9mm', 'Vector SBR 9mm', 'Vector SBR 9mm', 'smg', 'Vector SBR 9mm', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarketm60e6', 'blackmarketm60e6', '블랙마켓 M60 E6', 'Black Market M60 E6', 'lmg', 'Black Market M60 E6', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarketm60e6replica', 'blackmarketm60e6replica', '블랙마켓 M60 E6 리플리카', 'Black Market M60 E6 Replica', 'lmg', 'Black Market M60 E6 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarketrpk74e', 'blackmarketrpk74e', '블랙마켓 RPK-74 E', 'Black Market RPK-74 E', 'lmg', 'Black Market RPK-74 E', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarketrpk74ereplica', 'blackmarketrpk74ereplica', '블랙마켓 RPK-74 E 리플리카', 'Black Market RPK-74 E Replica', 'lmg', 'Black Market RPK-74 E Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:classicm60', 'classicm60', '클래식 M60', 'Classic M60', 'lmg', 'Classic M60', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:classicm60replica', 'classicm60replica', '클래식 M60 리플리카', 'Classic M60 Replica', 'lmg', 'Classic M60 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:classicrpk74', 'classicrpk74', '클래식 RPK-74', 'Classic RPK-74', 'lmg', 'Classic RPK-74', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:customl86a2', 'customl86a2', '커스텀 L86 A2', 'Custom L86 A2', 'lmg', 'Custom L86 A2', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:customl86a2replica', 'customl86a2replica', '커스텀 L86 A2 리플리카', 'Custom L86 A2 Replica', 'lmg', 'Custom L86 A2 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:gr9', 'gr9', 'GR9', 'GR9', 'lmg', 'GR9', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:infantrymg5', 'infantrymg5', '보병용 MG5', 'Infantry MG5', 'lmg', 'Infantry MG5', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:infantrymg5replica', 'infantrymg5replica', '보병용 MG5 리플리카', 'Infantry MG5 Replica', 'lmg', 'Infantry MG5 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:iwinegev', 'iwinegev', 'IWI Negev', 'IWI NEGEV', 'lmg', 'IWI NEGEV', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m249b', 'm249b', 'M249 B', 'M249 B', 'lmg', 'M249 B', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:mg5', 'mg5', 'MG5', 'MG5', 'lmg', 'MG5', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militaryl86lsw', 'militaryl86lsw', '군용 L86 LSW', 'Military L86 LSW', 'lmg', 'Military L86 LSW', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militarym60e4', 'militarym60e4', '군용 M60 E4', 'Military M60 E4', 'lmg', 'Military M60 E4', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militarymk46', 'militarymk46', '군용 MK46', 'Military MK46', 'lmg', 'Military MK46', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militarymk46replica', 'militarymk46replica', '군용 MK46 리플리카', 'Military MK46 Replica', 'lmg', 'Military MK46 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militaryrpk74m', 'militaryrpk74m', '군용 RPK-74 M', 'Military RPK-74 M', 'lmg', 'Military RPK-74 M', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:stonerlamg', 'stonerlamg', 'Stoner LAMG', 'Stoner LAMG', 'lmg', 'Stoner LAMG', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalm249para', 'tacticalm249para', '전술용 M249 Para', 'Tactical M249 Para', 'lmg', 'Tactical M249 Para', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:acs12', 'acs12', 'ACS-12', 'ACS-12', 'sg', 'ACS-12', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarketsasg12s', 'blackmarketsasg12s', '블랙마켓 SASG-12 S', 'Black Market SASG-12 S', 'sg', 'Black Market SASG-12 S', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:blackmarketsasg12sreplica', 'blackmarketsasg12sreplica', '블랙마켓 SASG-12 S 리플리카', 'Black Market SASG-12 S Replica', 'sg', 'Black Market SASG-12 S Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:customm870mcs', 'customm870mcs', '커스텀 M870 MCS', 'Custom M870 MCS', 'sg', 'Custom M870 MCS', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:customm870mcsreplica', 'customm870mcsreplica', '커스텀 M870 MCS 리플리카', 'Custom M870 MCS Replica', 'sg', 'Custom M870 MCS Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:doublebarrelsawedoff', 'doublebarrelsawedoff', '더블 배럴 소드 오프', 'Double Barrel Sawed Off', 'sg', 'Double Barrel Sawed Off', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:doublebarrelshotgun', 'doublebarrelshotgun', '더블 배럴 산탄총', 'Double Barrel Shotgun', 'sg', 'Double Barrel Shotgun', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:doublebarrelshotgunreplica', 'doublebarrelshotgunreplica', '더블 배럴 산탄총 리플리카', 'Double Barrel Shotgun Replica', 'sg', 'Double Barrel Shotgun Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:ksgshotgun', 'ksgshotgun', 'KSG Shotgun', 'KSG Shotgun', 'sg', 'KSG Shotgun', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m870express', 'm870express', '보급형 M870', 'M870 Express', 'sg', 'M870 Express', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m870expressreplica', 'm870expressreplica', '보급형 M870 리플리카', 'M870 Express Replica', 'sg', 'M870 Express Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:marinesuper90', 'marinesuper90', '해병대용 Super 90', 'Marine Super 90', 'sg', 'Marine Super 90', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militarym870', 'militarym870', '군용 M870', 'Military M870', 'sg', 'Military M870', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:sasg12', 'sasg12', 'SASG-12', 'SASG-12', 'sg', 'SASG-12', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:six12', 'six12', 'SIX12', 'SIX12', 'sg', 'SIX12', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:spas12', 'spas12', 'SPAS-12', 'SPAS-12', 'sg', 'SPAS-12', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:spas12replica', 'spas12replica', 'SPAS-12 리플리카', 'SPAS-12 Replica', 'sg', 'SPAS-12 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:super90', 'super90', 'Super 90', 'Super 90', 'sg', 'Super 90', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:super90replica', 'super90replica', 'Super 90 리플리카', 'Super 90 Replica', 'sg', 'Super 90 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalsasg12k', 'tacticalsasg12k', '전술용 SASG-12 K', 'Tactical SASG-12 K', 'sg', 'Tactical SASG-12 K', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalsuper90sbs', 'tacticalsuper90sbs', '전술용 Super 90 SBS', 'Tactical Super 90 SBS', 'sg', 'Tactical Super 90 SBS', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalsuper90sbsreplica', 'tacticalsuper90sbsreplica', '전술용 Super 90 SBS 리플리카', 'Tactical Super 90 SBS Replica', 'sg', 'Tactical Super 90 SBS Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:586magnum', '586magnum', '586 Magnum', '586 Magnum', 'pistol', '586 Magnum', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:93r', '93r', '93R', '93R', 'pistol', '93R', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:custompf45', 'custompf45', '커스텀 PF45', 'Custom PF45', 'pistol', 'Custom PF45', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:d50', 'd50', 'D50', 'D50', 'pistol', 'D50', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:diceros', 'diceros', 'Diceros', 'Diceros', 'pistol', 'Diceros', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:dicerosreplica', 'dicerosreplica', 'Diceros 리플리카', 'Diceros Replica', 'pistol', 'Diceros Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:firstwavepf45', 'firstwavepf45', '1차 투입 요원용 PF45', 'First Wave PF45', 'pistol', 'First Wave PF45', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:kard45', 'kard45', 'KARD-45', 'KARD-45', 'pistol', 'KARD-45', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m1911', 'm1911', 'M1911', 'M1911', 'pistol', 'M1911', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:m45a1', 'm45a1', 'M45A1', 'M45A1', 'pistol', 'M45A1', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militarym9', 'militarym9', '군용 M9', 'Military M9', 'pistol', 'Military M9', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:militarym9replica', 'militarym9replica', '군용 M9 리플리카', 'Military M9 Replica', 'pistol', 'Military M9 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:officersm9a1', 'officersm9a1', '장교용 M9 A1', 'Officer''s M9 A1', 'pistol', 'Officer''s M9 A1', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:police686magnum', 'police686magnum', '경찰용 686 Magnum', 'Police 686 Magnum', 'pistol', 'Police 686 Magnum', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:police686magnumreplica', 'police686magnumreplica', '경찰용 686 Magnum 리플리카', 'Police 686 Magnum Replica', 'pistol', 'Police 686 Magnum Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:px4stormtypef', 'px4stormtypef', 'Px4 Storm Type F', 'Px4 Storm Type F', 'pistol', 'Px4 Storm Type F', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:px4stormtypet', 'px4stormtypet', 'Px4 Storm Type T', 'Px4 Storm Type T', 'pistol', 'Px4 Storm Type T', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:px4stormtypetreplica', 'px4stormtypetreplica', 'Px4 Storm Type T 리플리카', 'Px4 Storm Type T Replica', 'pistol', 'Px4 Storm Type T Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:snubnoseddiceros', 'snubnoseddiceros', 'Snubnosed Diceros', 'Snubnosed Diceros', 'pistol', 'Snubnosed Diceros', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalm1911', 'tacticalm1911', '전술용 M1911', 'Tactical M1911', 'pistol', 'Tactical M1911', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:tacticalm1911replica', 'tacticalm1911replica', '전술용 M1911 리플리카', 'Tactical M1911 Replica', 'pistol', 'Tactical M1911 Replica', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:x45', 'x45', 'X-45', 'X-45', 'pistol', 'X-45', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:x45tactical', 'x45tactical', 'X-45 Tactical', 'X-45 Tactical', 'pistol', 'X-45 Tactical', 'highend', null, null, null, null);
insert into weapon_models (item_key, name_key, name_ko, name_en, weapon_group, family, rarity_tier, rpm, base_mag_size, base_damage, optimal_range) values ('weapon:x45tacticalreplica', 'x45tacticalreplica', 'X-45 Tactical 리플리카', 'X-45 Tactical Replica', 'pistol', 'X-45 Tactical Replica', 'highend', null, null, null, null);
